import {
  MlPredictionResult,
  PredictionHistoryItem,
  ProjectRiskLevel,
  StagePredictionItem,
  StageName,
  UserRole,
} from '../types';
import { INITIAL_PREDICTION_PRJ_1042, PREDICTION_HISTORY_DATA } from '../data/mlPredictionData';
import { getDataset } from './datasetGateway';
import { landAcquisitionApi } from './landAcquisitionApi';

// In-memory cache for runtime predictions
const predictionsStore: Record<string, MlPredictionResult> = {
  'PRJ-1042': { ...INITIAL_PREDICTION_PRJ_1042 },
};

const historyStore: Record<string, PredictionHistoryItem[]> = {
  ...PREDICTION_HISTORY_DATA,
};

export interface PredictionPipelineStep {
  stepNumber: number;
  label: string;
  detail: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  timestamp?: string;
}

export interface PredictionSimulationOptions {
  disputeFastTrack?: boolean;
  compensationPacePercent?: number;
  rrPackageConsensusPercent?: number;
  tahsildarKhataCampActive?: boolean;
  forceOutdated?: boolean;
  forceBlocked?: boolean;
}

function mapRealAnalysis(projectId: string, analysis: Record<string, unknown>): MlPredictionResult {
  const delayDays = Number(analysis.predicted_delay_days || 0);
  const riskLevel = (String(analysis.risk_level || 'LOW').toUpperCase()) as ProjectRiskLevel;
  const riskScore = Number(analysis.risk_score || 0) / 100;
  const drivers = Array.isArray(analysis.top_drivers) ? analysis.top_drivers as Array<Record<string, unknown>> : [];
  const factors = drivers.map((driver) => ({ factor: String(driver.feature || 'Model feature'), stage: 'Compensation' as StageName, impactPercentage: Math.round(Number(driver.influence || 0) * 100), description: `Observed value: ${String(driver.value ?? 'n/a')}` }));
  const stage = (name: StageName, number: number): StagePredictionItem => ({ stage: name, stageNumber: number, stageCode: `STG-${String(number).padStart(2, '0')}`, delayProbability: Number(analysis.risk_score || 0), riskScore, expectedDelayMonths: Number((delayDays / 30).toFixed(1)), expectedDelayDays: Math.round(delayDays), riskLevel, status: 'Model result available', keyRiskFactors: factors.slice(0, 2).map((factor) => factor.factor), mitigationAction: String(analysis.recommended_action || 'Review the model drivers with the concerned department.') });
  return {
    ...INITIAL_PREDICTION_PRJ_1042,
    projectId,
    projectName: `Project ${projectId}`,
    status: 'AVAILABLE',
    overall: { ...INITIAL_PREDICTION_PRJ_1042.overall, delayProbability: Number(analysis.risk_score || 0), riskScore, expectedDelayMonths: Number((delayDays / 30).toFixed(1)), expectedDelayDays: Math.round(delayDays), riskLevel, overallStatus: 'Real model inference from the uploaded project snapshot' },
    stages: (['Notification', 'Verification', 'Approval', 'Compensation', 'Legal', 'R&R', 'Possession'] as StageName[]).map((name, index) => stage(name, index + 1)),
    summaryExplanation: String(analysis.note || 'Prediction generated by the trained BhoomiDrishti model.'),
    topRiskContributors: factors,
    metadata: { ...INITIAL_PREDICTION_PRJ_1042.metadata, predictionId: `REAL-${Date.now()}`, datasetVersion: 'Uploaded project snapshot', predictionTimestamp: new Date().toLocaleString('en-IN'), dataSnapshotTimestamp: new Date().toISOString(), modelType: 'Trained GradientBoostingRegressor', algorithm: 'GradientBoostingRegressor' },
  };
}

/**
 * Backend API Client & ML Inference Gateway Simulator
 * Enforces authentication, validation gatekeeping, and feature calculation.
 */
export const mlPredictionService = {
  /**
   * Fetches latest ML prediction for a given project.
   * Enforces validation gating: returns BLOCKED if project data is invalid.
   */
  async getLatestPrediction(
    projectId: string = 'PRJ-1042',
    isValidationBlocked: boolean = false
  ): Promise<MlPredictionResult> {
    if (isValidationBlocked) {
      return {
        ...INITIAL_PREDICTION_PRJ_1042,
        projectId,
        status: 'BLOCKED',
        summaryExplanation:
          'Prediction calculation is currently BLOCKED because the underlying project dataset contains unverified schema or relational validation errors. Resolve all blocking validation issues in the Data Validation module before triggering the ML pipeline.',
      };
    }

    try {
      const saved = await landAcquisitionApi.getRiskAssessment(projectId);
      return mapRealAnalysis(projectId, saved);
    } catch {
      return {
        ...INITIAL_PREDICTION_PRJ_1042,
        projectId,
        status: 'BLOCKED',
        summaryExplanation: 'No real model result exists for this project yet. Upload a validated Excel snapshot and run the ML pipeline first.',
      };
    }
  },

  /**
   * Executes the ML Inference Pipeline with real-time step streaming.
   * Simulates async server-side ensemble inference on the latest validated dataset.
   */
  async executePredictionPipeline(
    projectId: string = 'PRJ-1042',
    userRole: UserRole = 'Administrator',
    options?: PredictionSimulationOptions,
    onProgressStep?: (step: number, logs: string[]) => void
  ): Promise<MlPredictionResult> {
    const dataset = await getDataset(projectId, 'field') || await getDataset(projectId, 'compensation') || await getDataset(projectId, 'land');
    if (dataset) {
      if (!/\.(xlsx|xlsm)$/i.test(dataset.fileName)) {
        throw new Error('The real ML service requires an .xlsx or .xlsm workbook for analysis.');
      }
      const file = new File([dataset.file], dataset.fileName, { type: dataset.fileType });
      const analysis = await landAcquisitionApi.analyzeWorkbook(projectId, file);
      const realResult = mapRealAnalysis(projectId, analysis);
      predictionsStore[projectId] = realResult;
      return realResult;
    }
    throw new Error('No Excel snapshot is stored for this project. Upload a workbook before running the real model.');
    const logs: string[] = [];
    const pushLog = (msg: string) => {
      const ts = new Date().toTimeString().split(' ')[0];
      logs.push(`[${ts}] ${msg}`);
    };

    // Step 1: Validating Project Data
    pushLog(`Initiating ML prediction request for ${projectId} by ${userRole}...`);
    pushLog('Checking authorization tokens and project-level RBAC grants... OK');
    if (onProgressStep) onProgressStep(1, [...logs]);
    await new Promise((res) => setTimeout(res, 350));

    // Step 2: Extracting Features
    pushLog('Extracting 48 statutory, spatial, and financial features from validated snapshot...');
    pushLog('Ingesting GIS shapefile overlap polygons, DoLR cadastral node parameters, and PFMS disbursement logs...');
    if (onProgressStep) onProgressStep(2, [...logs]);
    await new Promise((res) => setTimeout(res, 450));

    // Step 3: Running ML Ensemble
    pushLog('Loading Bhoomi-XGBoost-Ensemble-v3.4.2 model weights into memory...');
    pushLog('Executing Gradient Boosted Classifier with Calibrated Probability Head...');
    if (onProgressStep) onProgressStep(3, [...logs]);
    await new Promise((res) => setTimeout(res, 550));

    // Step 4: Generating Stage Predictions
    pushLog('Computing stage-wise Monte Carlo probability distributions across 7 acquisition phases...');
    pushLog('Applying RFCTLARR Section 24/25/64 legal timeline constraint penalty matrices...');
    if (onProgressStep) onProgressStep(4, [...logs]);
    await new Promise((res) => setTimeout(res, 400));

    // Calculate dynamic impacts based on options
    const compensationBoost = options?.compensationPacePercent ? (options.compensationPacePercent - 54) * 0.4 : 0;
    const fastTrackBoost = options?.disputeFastTrack ? 24 : 0;
    const tahsildarBoost = options?.tahsildarKhataCampActive ? 12 : 0;
    const rrBoost = options?.rrPackageConsensusPercent ? (options.rrPackageConsensusPercent - 62) * 0.3 : 0;

    const baseDelayProb = 72.4;
    const computedDelayProb = Math.max(18.5, Math.min(96.0, Number((baseDelayProb - (compensationBoost + fastTrackBoost + tahsildarBoost + rrBoost)).toFixed(1))));
    
    const computedRiskScore = Number((computedDelayProb / 100).toFixed(2));
    const computedDelayMonths = Math.max(1.2, Number((computedDelayProb * 0.088).toFixed(1)));
    const computedDelayDays = Math.round(computedDelayMonths * 30);

    const computedRiskLevel: ProjectRiskLevel =
      computedDelayProb >= 75 ? 'CRITICAL' : computedDelayProb >= 55 ? 'HIGH' : computedDelayProb >= 35 ? 'MEDIUM' : 'LOW';

    // Update stages dynamically
    const stages: StagePredictionItem[] = [
      {
        stage: 'Notification',
        stageNumber: 1,
        stageCode: 'STG-01',
        delayProbability: Math.max(10, Number((34.2 - (tahsildarBoost * 0.2)).toFixed(1))),
        riskScore: 0.34,
        expectedDelayMonths: 0.8,
        expectedDelayDays: 24,
        riskLevel: 'LOW',
        status: 'On Track',
        keyRiskFactors: ['Section 3A Gazette publication finalized', 'Minor survey gap in 2 cadastral boundaries'],
        mitigationAction: 'Issue addendum corrigendum for unlisted survey sub-divisions.',
        completionRatePercent: 92,
        confidenceScore: 94.1,
      },
      {
        stage: 'Verification',
        stageNumber: 2,
        stageCode: 'STG-02',
        delayProbability: Math.max(15, Number((48.6 - tahsildarBoost).toFixed(1))),
        riskScore: 0.45,
        expectedDelayMonths: 1.1,
        expectedDelayDays: 33,
        riskLevel: tahsildarBoost > 0 ? 'LOW' : 'MEDIUM',
        status: tahsildarBoost > 0 ? 'On Track' : 'Moderate Risk',
        keyRiskFactors: ['Joint succession khata verification backlog at Tehsil office', '38 unlinked Aadhaar records in PAF roster'],
        mitigationAction: 'Deploy Special Tahsildar camp for on-spot khatedar identity verification.',
        completionRatePercent: 86,
        confidenceScore: 91.0,
      },
      {
        stage: 'Approval',
        stageNumber: 3,
        stageCode: 'STG-03',
        delayProbability: 28.5,
        riskScore: 0.29,
        expectedDelayMonths: 0.6,
        expectedDelayDays: 18,
        riskLevel: 'LOW',
        status: 'On Track',
        keyRiskFactors: ['Competent Authority statutory sanction received', 'State Level Empowered Committee clearance in progress'],
        mitigationAction: 'Automate digital sanction routing via BhoomiDrishti portal.',
        completionRatePercent: 88,
        confidenceScore: 96.2,
      },
      {
        stage: 'Compensation',
        stageNumber: 4,
        stageCode: 'STG-04',
        delayProbability: Math.max(20, Number((79.1 - compensationBoost * 2).toFixed(1))),
        riskScore: Number(((79.1 - compensationBoost * 2) / 100).toFixed(2)),
        expectedDelayMonths: Number(Math.max(0.5, 2.1 - compensationBoost * 0.05).toFixed(1)),
        expectedDelayDays: Math.round(Math.max(15, 63 - compensationBoost * 1.5)),
        riskLevel: (79.1 - compensationBoost * 2) > 70 ? 'CRITICAL' : 'HIGH',
        status: (79.1 - compensationBoost * 2) > 70 ? 'Critical Delay' : 'Moderate Risk',
        keyRiskFactors: ['PFMS Direct Benefit Transfer escrow account disbursement bottleneck', '₹18.4 Cr pending in contested joint award shares'],
        mitigationAction: 'Activate Special Land Acquisition Officer (SLAO) fast-track DBT disbursement window.',
        completionRatePercent: 68,
        confidenceScore: 89.4,
      },
      {
        stage: 'Legal',
        stageNumber: 5,
        stageCode: 'STG-05',
        delayProbability: Math.max(25, Number((86.7 - fastTrackBoost).toFixed(1))),
        riskScore: Number(((86.7 - fastTrackBoost) / 100).toFixed(2)),
        expectedDelayMonths: Number(Math.max(0.8, 2.6 - fastTrackBoost * 0.06).toFixed(1)),
        expectedDelayDays: Math.round(Math.max(24, 78 - fastTrackBoost * 1.8)),
        riskLevel: (86.7 - fastTrackBoost) > 70 ? 'CRITICAL' : 'HIGH',
        status: (86.7 - fastTrackBoost) > 70 ? 'Critical Delay' : 'Moderate Risk',
        keyRiskFactors: ['14 active writ petitions under Section 64 reference in High Court', 'Stay order active on 3 commercial corridor parcels'],
        mitigationAction: 'Constitute dedicated Revenue Court Tribunal Special Bench for day-to-day hearings.',
        completionRatePercent: 46,
        confidenceScore: 84.8,
      },
      {
        stage: 'R&R',
        stageNumber: 6,
        stageCode: 'STG-06',
        delayProbability: Math.max(18, Number((61.3 - rrBoost).toFixed(1))),
        riskScore: 0.52,
        expectedDelayMonths: 1.2,
        expectedDelayDays: 36,
        riskLevel: (61.3 - rrBoost) > 60 ? 'HIGH' : 'MEDIUM',
        status: (61.3 - rrBoost) > 60 ? 'Moderate Risk' : 'On Track',
        keyRiskFactors: ['Rehabilitation package award valuation disputes across 2 village clusters', 'Resettlement colony civic infrastructure tender delayed'],
        mitigationAction: 'Execute Gram Sabha structured consensus alignment & upfront annuity disbursement.',
        completionRatePercent: 74,
        confidenceScore: 87.3,
      },
      {
        stage: 'Possession',
        stageNumber: 7,
        stageCode: 'STG-07',
        delayProbability: Math.max(22, Number((74.8 - (fastTrackBoost * 0.4 + compensationBoost * 0.3)).toFixed(1))),
        riskScore: 0.65,
        expectedDelayMonths: 1.5,
        expectedDelayDays: 45,
        riskLevel: 'HIGH',
        status: 'Critical Delay',
        keyRiskFactors: ['Physical site handover contingent upon Section 64 dispute resolution', 'Agricultural crop harvesting window clearance requested by farmers'],
        mitigationAction: 'Coordinate phased staggered possession handing over clear unencumbered stretches first.',
        completionRatePercent: 50,
        confidenceScore: 85.9,
      },
    ];

    // Step 5: Committing to Immutable Ledger
    const newPredictionId = `PRED-2026-${Date.now().toString().slice(-6)}`;
    const nowStr = new Date().toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    pushLog(`Prediction successfully generated! Prediction ID: ${newPredictionId}`);
    pushLog('Committed prediction payload to BhoomiDrishti immutable audit ledger.');
    if (onProgressStep) onProgressStep(5, [...logs]);
    await new Promise((res) => setTimeout(res, 300));

    const result: MlPredictionResult = {
      projectId,
      projectName: 'NH-216 Land Acquisition',
      location: 'Andhra Pradesh',
      status: 'AVAILABLE',
      overall: {
        delayProbability: computedDelayProb,
        riskScore: computedRiskScore,
        expectedDelayMonths: computedDelayMonths,
        expectedDelayDays: computedDelayDays,
        confidence: 89.2,
        riskLevel: computedRiskLevel,
        modelConfidenceGrade: 'High',
        overallStatus: computedDelayProb > 60 ? 'Critical Timeline Vulnerability Detected' : 'Manageable Timeline Risk',
      },
      stages,
      summaryExplanation: `The ensemble ML model predicts a ${computedRiskLevel.toLowerCase()} probability of delay (${computedDelayProb}%, risk score ${computedRiskScore}/1.00), with an expected cumulative schedule slippage of ${computedDelayMonths} months (${computedDelayDays} days). Primary bottlenecks remain in ${stages.filter(s => s.riskLevel === 'CRITICAL' || s.riskLevel === 'HIGH').map(s => s.stage).join(' and ')}.`,
      topRiskContributors: INITIAL_PREDICTION_PRJ_1042.topRiskContributors,
      metadata: {
        ...INITIAL_PREDICTION_PRJ_1042.metadata,
        predictionId: newPredictionId,
        predictionTimestamp: nowStr,
        datasetVersion: 'DS-PRJ1042-REV-09',
        dataSnapshotTimestamp: nowStr,
      },
      isDataFresh: true,
      dataChangesSincePrediction: 0,
    };

    // Save to store
    predictionsStore[projectId] = result;

    // Add to history
    const historyItem: PredictionHistoryItem = {
      id: newPredictionId,
      projectId,
      generatedAt: nowStr,
      modelVersion: result.metadata.modelVersion,
      datasetVersion: result.metadata.datasetVersion,
      riskLevel: computedRiskLevel,
      delayProbability: computedDelayProb,
      expectedDelayMonths: computedDelayMonths,
      status: 'AVAILABLE',
      triggeredBy: `${userRole} (Session Run)`,
      remarks: options?.disputeFastTrack || options?.compensationPacePercent
        ? 'Scenario simulation run with adjusted intervention parameters.'
        : 'Automated ML inference cycle triggered by user.',
    };

    if (!historyStore[projectId]) {
      historyStore[projectId] = [];
    }
    historyStore[projectId] = [
      historyItem,
      ...historyStore[projectId].map((h) => ({ ...h, status: 'SUPERSEDED' as const })),
    ];

    return result;
  },

  /**
   * Fetches prediction history for a project.
   */
  async getPredictionHistory(projectId: string = 'PRJ-1042'): Promise<PredictionHistoryItem[]> {
    return historyStore[projectId] || [];
  },
};
